chab\TestTourBundle\Entity\City:
    type: entity
    table: null
    repositoryClass: chab\TestTourBundle\Entity\CityRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        info:
            type: string
            length: 255
            fixed: false
            nullable: false
    oneToMany:
        Tour:
          targetEntity: chab\TestTourBundle\Entity\Tour
          cascade: { }
          mappedBy: id
          inversedBy: null
          joinColumns:
             id:
               referencedColumnName: city
          orphanRemoval: false

    lifecycleCallbacks: {  }
