<?php

namespace chab\TestTourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TourCategoryConn3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourCategoryConn3Repository extends EntityRepository
{
}
