<?php

namespace chab\TestTourBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TourCategoryConnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourCategoryConnRepository extends EntityRepository
{
}
