chab_test_tour_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: chabTestTourBundle:Default:index }
city:
    pattern:  /
    defaults: { _controller: "chabTestTourBundle:City:index" }

city_show:
    pattern:  /city2/{id}/show
    defaults: { _controller: "chabTestTourBundle:City:show" }

city_new:
    pattern:  /city2/new
    defaults: { _controller: "chabTestTourBundle:City:new" }

city_create:
    pattern:  /city2/create
    defaults: { _controller: "chabTestTourBundle:City:create" }
    requirements: { _method: post }

city_edit:
    pattern:  /city2/{id}/edit
    defaults: { _controller: "chabTestTourBundle:City:edit" }

city_update:
    pattern:  /city2/{id}/update
    defaults: { _controller: "chabTestTourBundle:City:update" }
    requirements: { _method: post|put }

city_delete:
    pattern:  /city2/{id}/delete
    defaults: { _controller: "chabTestTourBundle:City:delete" }
    requirements: { _method: post|delete }


tour:
    pattern:  /tour2/
    defaults: { _controller: "chabTestTourBundle:Tour:index" }

tour_show:
    pattern:  /tour2/{id}/show
    defaults: { _controller: "chabTestTourBundle:Tour:show" }

tour_new:
    pattern:  /tour2/new
    defaults: { _controller: "chabTestTourBundle:Tour:new" }

tour_create:
    pattern:  /tour2/create
    defaults: { _controller: "chabTestTourBundle:Tour:create" }
    requirements: { _method: post }

tour_edit:
    pattern:  /tour2/{id}/edit
    defaults: { _controller: "chabTestTourBundle:Tour:edit" }

tour_update:
    pattern:  /tour2/{id}/update
    defaults: { _controller: "chabTestTourBundle:Tour:update" }
    requirements: { _method: post|put }

tour_delete:
    pattern:  /tour2/{id}/delete
    defaults: { _controller: "chabTestTourBundle:Tour:delete" }
    requirements: { _method: post|delete }



category:
    pattern:  /categ/
    defaults: { _controller: "chabTestTourBundle:Category:index" }

category_show:
    pattern:  /categ/{id}/show
    defaults: { _controller: "chabTestTourBundle:Category:show" }

category_new:
    pattern:  /categ/new
    defaults: { _controller: "chabTestTourBundle:Category:new" }

category_create:
    pattern:  /categ/create
    defaults: { _controller: "chabTestTourBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    pattern:  /categ/{id}/edit
    defaults: { _controller: "chabTestTourBundle:Category:edit" }

category_update:
    pattern:  /categ/{id}/update
    defaults: { _controller: "chabTestTourBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    pattern:  /categ/{id}/delete
    defaults: { _controller: "chabTestTourBundle:Category:delete" }
    requirements: { _method: post|delete }
